### ISSUE TITLE
Update Version for Latest Dalamud

### ISSUE THREAD

**Issue by XxInvictus** [Caraxi/AutoLogin#3]
I have placed the current version of this plugin in my Dev folder to force it to load with the latest version and can confirm it is working correctly. You should just be able to just update API version and mod version and be good to go 👍

**Comment by Theletha** [comment]
is it still working for you? Is this what we need to do to make it work?

**Comment by XxInvictus** [comment]
I think I ended up sourcing from a new repo, gonna close this as it seems dead.

**Comment by Theletha** [comment]
same
